Support for package.source
soniaai/rules_poetry pull request #5
Opened 2020-11-17 11:33 UTC by sjoerdvisscher

Fixes issue #4

Note that I'm not sure if checking that the source type is `legacy` is the right thing to do, that just happened to be the value in my case.

2020-11-18 04:10 UTC, NathanHowell requested changes
can you switch to None instead of an empty string for the default? otherwise it looks good to me

2020-11-18 11:28 UTC, sjoerdvisscher commented
I tried, but that doesn't work nicely with generating code using a template. (It seems you came to the same conclusion with `marker`, which also has the empty string as default.)

2020-11-19 01:33 UTC, NathanHowell approved these changes

2020-11-19 01:33 UTC, merged

2020-11-19 01:34 UTC, NathanHowell commented
makes sense, thanks for the PR